Add reducer and actions
Thi-Ponce/Bookstore pull request #2
Opened 2022-03-30 23:14 UTC by Thi-Ponce

### Lesson Objective:
- Understand the concept of state management.
- Use store, actions, and reducers in React.

2022-03-30 23:36 UTC, Meltrust requested changes
Hi @Thi-Ponce,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Nice reducers!✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 23:36 UTC, Meltrust commented on src/redux/books/books.js
> +const REMOVEBOOK = 'REMOVEBOOK';
- [ ] Please, kindly follow the Ducks pattern for the value of each action like this:

```JAVASCRIPT
const ADD_BOOK = 'bookStore/books/ADD_BOOK';
const REMOVE_BOOK = 'bookStore/books/REMOVE_BOOK';
```

That way, we will meet this requirement 💪

2022-03-30 23:36 UTC, Meltrust commented on src/redux/categories/categories.js
> +const CHECKSTATUS = 'CHECKSTATUS';
- [ ] Please, kindly follow the Ducks pattern for the value of each action like this:

```JAVASCRIPT
const CHECK_STATUS = 'bookStore/books/CHECK_STATUS';
```

That way, we will meet this requirement 💪

2022-03-31 16:14 UTC, eri8-9 approved these changes
Hi @Thi-Ponce, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Well done!

![Felix](https://media.giphy.com/media/hlQeY3PbhH3i/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 16:39 UTC, merged