Add styling
Thi-Ponce/Bookstore pull request #5
Opened 2022-04-01 22:29 UTC by Thi-Ponce

### Lesson objectives: 
- Understand the concept of state management.
- Use store, actions and reducers in React.
- Connect React and Redux.
- Apply React best practices and language style guides in code.

2022-04-01 23:42 UTC, Meltrust requested changes
Hi @Thi-Ponce,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Great general styling! ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 23:42 UTC, Meltrust commented on src/components/Home.css
> +
- [x] On your CSS rules, please declare your 'font-family' rules as `Roboto Slab` instead of `RobotoSlab`.  That way, your Roboto Slab font family will render correctly 💪

2022-04-01 23:42 UTC, Meltrust commented on src/components/Home.css
> +
Some fonts stylings in your project do not match the given design.

Therefore::

- [x] Please, check all your fonts and correct them so the exact font styling is matched from the Zeplin to your project.

## Explanation

We need to achieve an exact copy of the Zeplin project.  That includes the fonts stylings.  The fonts stylings include font-family, font-weight, letter-spacing, font-height, font-size, font-stretch, color.

## Hints

Look:

![image](https://user-images.githubusercontent.com/57421823/161323544-4aacf083-e221-4b75-9457-4641652f5b08.png)

Just check the font stylings on the Zeplin and make sure they match your project! 💪

2022-04-01 23:42 UTC, Meltrust commented on src/components/Home.css
> +
Good job with the general design, however, some of the elements do not match the Zeplin.

Look:

![image](https://user-images.githubusercontent.com/57421823/161352514-4df649df-0f14-460d-b8c3-61b0cf221968.png)

Therefore:

- [ ] Please, align the booklist section with the form section, so the alignment matches.  Please make sure that the big horizontal line between these 2 sections matches the alignment too.
- [ ] According to the Zeplin, the form section does not feature borders.  Please, remove them so your project looks like the zeplin.
- [ ] The category input and the "add button" are being sent to the next line.  Please, kindly resize your "title" and "author" inputs so they are shorter and make sure the whole form (all the inputs and the submit button) fits and renders in just one line.  This is an example:
![image](https://user-images.githubusercontent.com/57421823/161352969-706e5659-323a-4b4d-b71f-0d308b53190b.png)
- [ ] The borders featured on the page are the wrong width.  (You mostly make them 2px, they should be just 1 px).  Please, make them the right width.

If you implement these changes, your project will look more like the Zeplin! 💪

2022-04-02 02:45 UTC, BrianSammit approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @Thi-Ponce, 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-02 02:50 UTC, merged